name        : rlwrap
version     : 0.42
release     : 2
source      :
    - https://github.com/hanslub42/rlwrap/archive/v0.42.tar.gz : fff56c24341f0c717cf3a8f0ebbf2cba415b1952e1591168ca69ed13638b20f3
license     :
    - GPL-2.0
component   : system.util
homepage    : https://github.com/hanslub42/rlwrap
summary     : a readline wrapper
description : |
    rlwrap is a 'readline wrapper', a small utility that uses the GNU readline library to allow the editing of keyboard input for any command
setup       : |
    %reconfigure
build       : |
    %make
install     : |
    %make_install
