name       : rlwrap
version    : 0.45.2
release    : 5
source     :
    - https://github.com/hanslub42/rlwrap/releases/download/v0.45.2/rlwrap-0.45.2.tar.gz : 9f8870deb46e473d21b5db89d709b6497f4ef9fa06d44eebc5f821daa00c8eca
license    : GPL-2.0-or-later
component  : system.util
homepage   : https://github.com/hanslub42/rlwrap
summary    : rlwrap is a readline wrapper
description: |
    rlwrap is a readline wrapper, a small utility that uses the GNU readline library to allow the editing of keyboard input for any command
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
