name       : rlwrap
version    : '0.43'
release    : 3
source     :
    - https://github.com/hanslub42/rlwrap/releases/download/v0.43/rlwrap-0.43.tar.gz : 8e86d0b7882d9b8a73d229897a90edc207b1ae7fa0899dca8ee01c31a93feb2f
license    : GPL-2.0-or-later
component  : system.util
homepage   : https://github.com/hanslub42/rlwrap
summary    : rlwrap is a readline wrapper
description: |
    rlwrap is a readline wrapper, a small utility that uses the GNU readline library to allow the editing of keyboard input for any command
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
